package form;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NGUYEN DUC CUONG
 */
public class LoadingForm extends javax.swing.JFrame {

    /**
     * Creates new form LoadingForm
     */
    public LoadingForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPenal = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        LoadingValue10 = new javax.swing.JLabel();
        LoadingLabel10 = new javax.swing.JLabel();
        LoadingBar10 = new javax.swing.JProgressBar();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackgroundPenal.setBackground(new java.awt.Color(255, 255, 51));
        BackgroundPenal.setMinimumSize(new java.awt.Dimension(750, 450));
        BackgroundPenal.setPreferredSize(new java.awt.Dimension(700, 400));
        BackgroundPenal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("PHẦN MỀM QUẢN LÝ ĐỀ TÀI NGHIÊN CỨU KHOA HỌC");
        BackgroundPenal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 540, 50));

        LoadingValue10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LoadingValue10.setText("%");
        BackgroundPenal.add(LoadingValue10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, -1));

        LoadingLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LoadingLabel10.setText("Loading...");
        BackgroundPenal.add(LoadingLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        LoadingBar10.setForeground(new java.awt.Color(255, 102, 204));
        BackgroundPenal.add(LoadingBar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 700, 20));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hinh.gif"))); // NOI18N
        BackgroundImage.setMaximumSize(new java.awt.Dimension(700, 400));
        BackgroundImage.setMinimumSize(new java.awt.Dimension(700, 400));
        BackgroundImage.setPreferredSize(new java.awt.Dimension(700, 400));
        BackgroundPenal.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPenal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPenal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoadingForm().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoadingForm().setVisible(true);
//            }
//        });


 LoadingForm sp = new LoadingForm();
        sp.setVisible(true);
        for (int i = 0; i <= 100; i++) {
            try {
                Thread.sleep(100);
            
            sp.LoadingValue10.setText(i + "%");
            if (i == 10) {
                sp.LoadingLabel10.setText("Turning On Modules...");
            }
            if (i == 20) {
                sp.LoadingLabel10.setText("Loading Modules...");
            }
            if (i == 50) {
                sp.LoadingLabel10.setText("Connecting to Database...");
            }
            if (i == 70) {
                sp.LoadingLabel10.setText("Connecting to Succesfully...");
            }
            if (i == 80) {
                sp.LoadingLabel10.setText("Launching Application...");
            }
            sp.LoadingBar10.setValue(i);
            
            
            
            
            } catch (InterruptedException ex) {
                Logger.getLogger(LoadingForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        LoginForm lg = new LoginForm();
            lg.setVisible(true);
            sp.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BackgroundPenal;
    private javax.swing.JProgressBar LoadingBar10;
    private javax.swing.JLabel LoadingLabel10;
    private javax.swing.JLabel LoadingValue10;
    private javax.swing.JLabel jLabel10;
    // End of variables declaration//GEN-END:variables
}
