package form;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author TGDD
 */
public class registerForm extends javax.swing.JFrame {

    /**
     * Creates new form registerForm
     */
    public registerForm() {
        initComponents();
        setLocationRelativeTo(null);
        jfUsername.setBackground(new Color(0, 0, 0, 1));
        jfPassword.setBackground(new Color(0, 0, 0, 1));
        jfFullname.setBackground(new Color(0, 0, 0, 1));
        jfPhoneNumber.setBackground(new Color(0, 0, 0, 1));

    }

    private JPanel jPanelGradient() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    class jPanelGradient extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color1 = new Color(52, 143, 80);
            Color color2 = new Color(86, 180, 211);
            GradientPaint gp = new GradientPaint(0, 0, color1, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel containerPanel09 = new jPanelGradient();
        titleLb09 = new javax.swing.JLabel();
        closeBtn09 = new javax.swing.JLabel();
        usernameLb09 = new javax.swing.JLabel();
        jfUsername = new javax.swing.JTextField();
        passwordLb09 = new javax.swing.JLabel();
        jfPassword = new javax.swing.JTextField();
        fullnameLb09 = new javax.swing.JLabel();
        phonenumLb09 = new javax.swing.JLabel();
        jfPhoneNumber = new javax.swing.JTextField();
        signInBtn09 = new javax.swing.JButton();
        jfFullname = new javax.swing.JTextField();
        signInBtn10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titleLb09.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLb09.setForeground(new java.awt.Color(255, 255, 255));
        titleLb09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLb09.setText("Đăng ký tài khoản");

        closeBtn09.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        closeBtn09.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn09.setText("X");
        closeBtn09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtn09MouseClicked(evt);
            }
        });

        usernameLb09.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameLb09.setForeground(new java.awt.Color(255, 255, 255));
        usernameLb09.setText("Username      :  ");

        jfUsername.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jfUsername.setForeground(new java.awt.Color(255, 255, 255));
        jfUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jfUsername.setOpaque(false);
        jfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfUsernameActionPerformed(evt);
            }
        });

        passwordLb09.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLb09.setForeground(new java.awt.Color(255, 255, 255));
        passwordLb09.setText("Mật khẩu      :  ");

        jfPassword.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jfPassword.setForeground(new java.awt.Color(255, 255, 255));
        jfPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jfPassword.setOpaque(false);
        jfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfPasswordActionPerformed(evt);
            }
        });

        fullnameLb09.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fullnameLb09.setForeground(new java.awt.Color(255, 255, 255));
        fullnameLb09.setText("Họ và tên       :");

        phonenumLb09.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phonenumLb09.setForeground(new java.awt.Color(255, 255, 255));
        phonenumLb09.setText("Số điệnt thoại :");

        jfPhoneNumber.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jfPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        jfPhoneNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jfPhoneNumber.setOpaque(false);

        signInBtn09.setBackground(new java.awt.Color(153, 0, 51));
        signInBtn09.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signInBtn09.setForeground(new java.awt.Color(204, 255, 255));
        signInBtn09.setText("Đăng ký");
        signInBtn09.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        signInBtn09.setBorderPainted(false);
        signInBtn09.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signInBtn09.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        signInBtn09.setFocusable(false);
        signInBtn09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtn09ActionPerformed(evt);
            }
        });

        jfFullname.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jfFullname.setForeground(new java.awt.Color(255, 255, 255));
        jfFullname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jfFullname.setOpaque(false);
        jfFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfFullnameActionPerformed(evt);
            }
        });

        signInBtn10.setBackground(new java.awt.Color(51, 102, 0));
        signInBtn10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signInBtn10.setForeground(new java.awt.Color(204, 255, 255));
        signInBtn10.setText("Đăng nhập");
        signInBtn10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        signInBtn10.setBorderPainted(false);
        signInBtn10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signInBtn10.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        signInBtn10.setFocusable(false);
        signInBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtn10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerPanel09Layout = new javax.swing.GroupLayout(containerPanel09);
        containerPanel09.setLayout(containerPanel09Layout);
        containerPanel09Layout.setHorizontalGroup(
            containerPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanel09Layout.createSequentialGroup()
                .addGroup(containerPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanel09Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLb09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanel09Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(containerPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phonenumLb09, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(containerPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(usernameLb09, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addComponent(passwordLb09, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fullnameLb09, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(containerPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanel09Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeBtn09, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanel09Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(signInBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signInBtn09, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        containerPanel09Layout.setVerticalGroup(
            containerPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanel09Layout.createSequentialGroup()
                .addComponent(closeBtn09, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleLb09)
                .addGap(18, 18, 18)
                .addGroup(containerPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLb09)
                    .addComponent(jfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLb09)
                    .addComponent(jfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullnameLb09)
                    .addComponent(jfFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonenumLb09)
                    .addComponent(jfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(containerPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signInBtn09, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signInBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel09, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtn09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtn09MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtn09MouseClicked

    private void jfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfUsernameActionPerformed

    private void jfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfPasswordActionPerformed

    private void jfFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfFullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfFullnameActionPerformed

    private void signInBtn09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBtn09ActionPerformed
        try {
            // TODO add your handling code here:
            Connection connection = DBConnection.getConnection();
            String sql = "INSERT INTO dbo.[users](username,matkhau,fullname,sdt)" + "VALUES(?,?,?,?)";

            PreparedStatement ps = connection.prepareStatement(sql);

            ps.setNString(1, jfUsername.getText());
            ps.setString(2, jfPassword.getText());
            ps.setString(3, jfFullname.getText());
            ps.setString(4, jfPhoneNumber.getText());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Đăng ký thành công !!");
            DBConnection.closeConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(registerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signInBtn09ActionPerformed

    private void signInBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBtn10ActionPerformed
        // TODO add your handling code here:
        LoginForm lg = new LoginForm();
        lg.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_signInBtn10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeBtn09;
    private javax.swing.JLabel fullnameLb09;
    private javax.swing.JTextField jfFullname;
    private javax.swing.JTextField jfPassword;
    private javax.swing.JTextField jfPhoneNumber;
    private javax.swing.JTextField jfUsername;
    private javax.swing.JLabel passwordLb09;
    private javax.swing.JLabel phonenumLb09;
    private javax.swing.JButton signInBtn09;
    private javax.swing.JButton signInBtn10;
    private javax.swing.JLabel titleLb09;
    private javax.swing.JLabel usernameLb09;
    // End of variables declaration//GEN-END:variables
}
